// Code generated by github.com/godcong/dl. DO NOT EDIT.
// Version:
// Build Date: 2024-07-19 00:17:23
// Built By:
package example

func (obj *StructStdTest) Default() error {
	obj.FieldString = "test"
	obj.FieldInt = 1
	return nil
}
