{{/* The line below tells Intellij/GoLand to enable the autocompletion based on the *gen.Graph type. */}}
{{/* gotype: github.com/godcong/dl/gen.Graph */}}
{{- define "header"}}
// Code generated by github.com/godcong/dl. DO NOT EDIT.
// Version: {{ .GitVersion }}
// Commit: {{ .GitCommit }}
// Build Date: {{ .BuildDate }}
// Built By: {{ .BuiltBy }}
{{- end }}
package {{ $.Package }}

import (
    "github.com/godcong/dl"
{{- range $import := $.Imports }}
    {{ $import }}
{{ end -}}
)

{{- define "structs"}}
{{ range $s := $.Structs }}
{{- if $s.IsValid }}
// {{ $s.DefaultFuncName }} loads default values for {{ $s.Name }}
func (obj *{{ $s.Name }}) {{ $s.DefaultFuncName }}() error {
{{- range $f := $s.Fields }}
    {{- if $f.IsBasic }}
    obj.{{ $f.Name }} = {{ $f.Value }}
    {{- else }}
    if err := dl.Load(&obj.{{ $f.Name }}); err != nil {
        return err
    }
    {{- end }}
{{- end }}
    return nil
}
{{- end }}
{{- end }}
{{- end }}